var p1=24;
var p2=36;
var total =p1+p2;
console.log(total);
var total =p1-p2;
console.log(total);
var total =p1*p2;
console.log(total);
var total =p1/p2;
console.log(total);
var total =p2 % p1;
console.log(total);
var total =p1%p2;
console.log(total);
p1=p1+12;
p2++;
var total =p1+p2;
console.log(total);
p2--;
var total =p1+p2;
console.log(total);
p2='alo';
var total =p1+p2;
console.log(total);
p2='057';
var total =p1+p2;
console.log(total);
var p1='rabiul';
var p2='islam';
var total =p1+p2;
console.log(total);
var p1='rabiul';
var p2='islam';
var total =p1+' '+p2;
console.log(total);
